### ISSUE TITLE
printspoofer fails?

### ISSUE THREAD

**Issue by trickster0** [MythicAgents/Apollo#17]
Hello,

I have been trying to execute from a Domain Admin context on a domain connected host printspoofer to execute notepad as seen in the screenshot with SYSTEM privs or my bat which will execute the apollo payload to get a reverse shell but it seems to fail with error 5 (aka access denied). Not sure why...
It does say named pipe listening...Maybe because the smb beacons are not released yet?

![Untitled](https://user-images.githubusercontent.com/20028117/102517762-1ca9dc00-4099-11eb-8822-4c113c7b6185.png)

**Comment by djhohnstein** [comment]
No, what you're seeing is the output from this project here: https://github.com/itm4n/PrintSpoofer. I see that you're executing from a medium integrity callback, but the file you're attempting to execute exists outside of your user's home directories. Ensure that the file `C:\Users\user\Downloads\file.bat` is world-readable by all users before attempting to execute it

**Comment by trickster0** [comment]
hmm yes i just realized, interesting is this is a domain admin acc and it can read that file. Seems like i am indeed in medium integrity. How would you recommend elevation to high integrity through mythic? Since i was expecting to do this with printspoofer. I verified that administrator DA account can indeed read the file.

**Comment by djhohnstein** [comment]
If you are in the local Administrators group, you can bypass UAC using the `bypassuac` command. Otherwise, I'm assuming there's some error actually launching the .bat file (via file handlers or otherwise). You can ensure the `printspoofer` command is working by changing your command (to something like powershell.exe, for example), and if that works, you could try toying with exactly the right command to run. Going to close this issue for the time being, and for further questions you can forward them to the #mythic channel in the BloodhoundGang Slack, which can be joined here: https://bloodhoundgang.herokuapp.com/
